observerevent event type issue fixed
hansemannn/titanium-firebase-database pull request #2
Opened 2018-05-23 15:19 UTC by RavindraChherke

Looks like the MAKE_SYSTEM_PROP was not setting event values properly. I think keeping it in Module file is a good idea. Also, DATA_EVENT_TYPE_VALUE was set to FIRDataEventTypeChildAdded. Now changed to FIRDataEventTypeValue.

2018-05-23 15:36 UTC, hansemannn commented on ios/Classes/FirebaseDatabaseModule.m
> +MAKE_SYSTEM_PROP(DATA_EVENT_TYPE_CHANGE, FIRDataEventTypeChildChanged);
Looks good! One typo I noticed (that was in my initial implementation as well) is that we should include the `CHILD` phrase as well, e.g.:
- `DATA_EVENT_TYPE_CHILD_ADDED`
- `DATA_EVENT_TYPE_CHILD_REMOVED`
- `DATA_EVENT_TYPE_CHILD_MOVED`
- `DATA_EVENT_TYPE_CHILD_CHANGED`

Can you change that in code and docs?

2018-05-23 15:37 UTC, hansemannn requested changes
Left one review comment. Also, please bump the version in ios/manifest to the next patch version.

2018-05-23 16:12 UTC, RavindraChherke commented
I have made the changes as suggested. Please check. Thanks!

2018-05-23 16:48 UTC, hansemannn commented
It should be a patch bump (1.1.1) instead of a minor bump (1.2.0), referring to the [semver specs](https://semver.org/). Also, the constants should be suffixed with `_CHANGED` instead of `_CHANGE`. Please update that last piece and attach the new module version. Thx!

2018-05-24 06:49 UTC, RavindraChherke commented
Sorry, I should pay more attention to details. This is my first time contributing to other project.

I have build the module with Titanium SDK 7.1.1  There are changes in titanium.xcconfig. Is that OK?

Please find the attached zip file. 

[Uploading firebase.database-iphone-1.1.1.zip…](iOS 1.1.1)

2018-05-24 08:06 UTC, hansemannn commented
Looks perfect! PR **approved**. Keep up the great contributions to the community.

2018-05-24 08:06 UTC, hansemannn approved these changes

2018-05-24 08:06 UTC, merged

2018-05-24 08:08 UTC, hansemannn commented
New Release: https://github.com/hansemannn/titanium-firebase-database/releases/tag/ios-1.1.1